### PR TITLE
kata-deploy: Remove empty line

### PR DESCRIPTION
**Pull request by fidencio**
Remove an empty line from the line.
Fixes: #1234567890

Signed-off-by: Fabiano Fidêncio <fabiano.fidencio@intel.com>

### CODE REVIEW

**Comment by fidencio** [comment]
@egernst, can you trigger test-kata-deploy here?
I don't have enough perms :-)

**Comment by egernst** [comment]
PR is stale. I hope you don't mind, I'm closing it.

**Comment by fidencio** [comment]
:-)

**Pull request closed without merging**
